### PR TITLE
Add metadata for NEOK token

### PR DESCRIPTION
**Pull request by vrde**
:wave: we are NEOKingdom DAO, and our proposal to register our NEOK ERC20 as an IBC coin recently passed: https://app.evmos.org/governance?id=144

This PR is to add the metadata of our NEOKingdom DAO (NEOK) token.

(Thanks luisqa for the support)

### CODE REVIEW

**Comment by vrde** [comment]
@fedekunze @Mrsirdev is there anything blocking this PR to get merged :pray:?

**Comment by sirnicolaz** [comment]
@Mrsirdev as you seem to be the most active member in this repository, are you able to help us get this PR through? Or do you know who is in charge? It seems to be stagnating. Thank you!

**Comment by Mrsirdev** [comment]
Hey @sirnicolaz,

As discussed in the EVMOS Discord, we have so far only supported IBC tokens that are registered as ERC20 tokens.

This is the first instance of a native ERC20 token being registered as an IBC token, so we are uncertain if our backend and frontend will be compatible with this token type.

The EVMOS dashboard team has its own internal roadmap and priorities. We will prioritize working on and testing ERC20 tokens once we have resolved all previous priorities.

If this matter requires immediate attention, you can consider the following options:

A. Contribute to the open-source repositories of the assets page yourself to ensure compatibility with these token types and submit a pull request to add changes if needed. Both the frontend and backend of the assets page are open sourced.

B. Develop your own frontend implementation that enables users to transfer this ERC20 token registered as an IBC token to and from EVMOS.

C. Wait for the EVMOS dashboard team or other community members to add support for the existing dashboard.

Please bear in mind that the information contained in this repository is not arbitrary metadata. These configuration fields are used by the backend service to construct payloads for users to sign and broadcast IBC transfers.

**Comment by vrde** [comment]
> B. Develop your own frontend implementation that enables users to transfer this ERC20 token registered as an IBC token to and from EVMOS.

This is interesting, where can I find more info to do this? I found this module: https://github.com/evmos/evmosjs

And this example: https://github.com/evmos/evmosjs/blob/821639523ccb4b5d81fe23085e330009677d7d71/examples/messages/erc20/converters.md

Am I going to the right direction?

**Review by Mrsirdev — APPROVED** [review]

**Pull request merged**
